__author__ = 'vapaspen'
__name__ = 'sample-data'

'''
the_data ={
    "context": [
        "string",
        "string"
    ],
    "analysis": [
        "string",
        "string"
    ]
    "train":[
    [1.0, 0.0],
    [0.0, 1.0]
    ]
}"
'''

Train_Data_old = {
    '0': {
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.xml"
        ],
        "train": [
            [1.0, 0.0],
        ]
    },
    '1': {
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.xml",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\game.ico"
        ],
        "train": [
            [1.0, 0.0],
            [0.0, 1.0],
        ]
    },
    '2': {
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\SaveData.dat"
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\LevelData"
        ],
        "train": [
            [0.0, 1.0],
            [0.0, 1.0],
        ]
    },
    '3': {
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Besiege\\Besiege_Data\\Managed\\config.bat"
        ],
        "train": [
            [0.0, 1.0],
        ]
    },
    '4':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\ApexFrameworkSHIPPING_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\APEX_ClothingSHIPPING_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\binkw32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\BioShockInfinite.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\nvtt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\PhysX3_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\steam_api.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\Benchmark.bat",
        ],
        "train": [
            [1.0, 0.0],
        ]
    },
    '5':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\ApexFrameworkSHIPPING_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\APEX_ClothingSHIPPING_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\binkw32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\BioShockInfinite.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\nvtt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\PhysX3_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\steam_api.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\Benchmark.bat",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\game.icon",
        ],
        "train": [
            [1.0, 0.0],
            [0.0, 1.0],
        ]
    },
    '6':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\ApexFrameworkSHIPPING_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\APEX_ClothingSHIPPING_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\binkw32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\BioShockInfinite.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\nvtt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\PhysX3_x86.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\steam_api.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\BioShock Infinite\\Binaries\\Win32\\SaveGames.Dat",
        ],
        "train": [
            [0.0, 1.0],
        ]
    },
    '7':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\binkw32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Borderlands.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\cudart.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\dbghelp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\fmodex.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleFr.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleGr.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleIt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleLa.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleSp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleUk.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleUs.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\LangSelect.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\libresample.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\nvtt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\NxCooking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\ogg.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXCore.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXExtensions.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\SetupHelper.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\steam.log",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\SteamAPIUpdater.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\steam_api.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\UpdateDLLWrapper.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbis.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbisenc.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbisfile.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_adv_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_aui_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_core_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_dbgrid_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_gl_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_html_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_media_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_net_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_odbc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_qa_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_richtext_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_xml_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_xrc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_adv_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_aui_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_core_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_dbgrid_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_gl_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_html_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_media_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_net_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_odbc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_qa_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_richtext_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_xml_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_xrc_vc_custom.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxRC",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxRes",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Windows",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Borderlands.ico",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXLocal",
        ],
        "train": [
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],

        ]
    },
    '8':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\binkw32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Borderlands.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\cudart.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\dbghelp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\fmodex.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleFr.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleGr.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleIt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleLa.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleSp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleUk.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleUs.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\LangSelect.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\libresample.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\nvtt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\NxCooking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\ogg.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXCore.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXExtensions.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\SetupHelper.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\steam.log",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\SteamAPIUpdater.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\steam_api.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\UpdateDLLWrapper.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbis.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbisenc.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbisfile.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_adv_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_aui_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_core_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_dbgrid_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_gl_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_html_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_media_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_net_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_odbc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_qa_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_richtext_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_xml_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_xrc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_adv_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_aui_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_core_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_dbgrid_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_gl_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_html_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_media_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_net_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_odbc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_qa_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_richtext_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_xml_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_xrc_vc_custom.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\bat.bat",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxRes",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Windows",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Borderlands.ico",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXLocal",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\player.plist",
        ],
        "train": [
            [0.0, 1.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],

        ]
    },
    '9':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\binkw32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\Borderlands.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\cudart.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\dbghelp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\fmodex.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleFr.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleGr.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleIt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleLa.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleSp.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleUk.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\FonixTtsDtSimpleUs.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\LangSelect.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\libresample.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\nvtt.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\NxCooking.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\ogg.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXCore.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\PhysXExtensions.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\SetupHelper.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\steam.log",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\SteamAPIUpdater.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\steam_api.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\UpdateDLLWrapper.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbis.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbisenc.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\vorbisfile.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_adv_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_aui_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_core_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_dbgrid_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_gl_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_html_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_media_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_net_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_odbc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_qa_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_richtext_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_xml_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28ud_xrc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_adv_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_aui_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_core_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_dbgrid_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_gl_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_html_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_media_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_net_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_odbc_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_qa_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_richtext_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_xml_vc_custom.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\wxmsw28u_xrc_vc_custom.dll",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\ffxivgame.bck",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\ffxivgame.ver",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\movie",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\borderlands\\Binaries\\sqpack",
        ],
        "train": [
            [0.0, 1.0],
            [0.0, 1.0],
            [1.0, 1.0],
            [1.0, 1.0],

        ]
    },
    '10':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w64.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxivgame.bck",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\fileinfo.fiin",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\movie",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxivgame.ver",
        ],
        "train": [
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
        ]
    },
	'11':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w64.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxivgame.bck",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\fileinfo.fiin",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\{f4n92df-dgsd}",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\system32",
        ],
        "train": [
            [1.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],
            [1.0, 0.0],
            [0.0, 1.0],
        ]
    },
	'12':{
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w32.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w64.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv.exe",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\eventvwr.msc",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\appwiz.cpl",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\new_folder",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\personal_data.dat",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\FINAL FANTASY XIV - A Realm Reborn\\game\\hosts",
        ],
        "train": [
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
        ]
    },
}

Test_Data_old = {
    '1': {
        "context": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXi.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXiMain.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXiResource.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXiVersions.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\config.sys",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ImeUiDll.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ImeUiDll2.dll",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\polboot.exe",
        ],
        "analysis": [
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_e.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_n.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_ne.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_nw.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_s.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_se.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_sw.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_w.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\file.txt",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\FTABLE.DAT",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\mousehit.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\mousenor.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\mousenor.cur",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\mov",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_e.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_n.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_ne.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_nw.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_s.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_se.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_sw.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_w.ani",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.cfg",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.rst",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.sin",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.txt",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.ver",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\patch2.cfg",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\polboot.exe.manifest",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM2",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM3",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM4",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM5",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM6",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM7",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM8",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\signature.DAT",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\sound",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\sound2",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\sound3",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\sound4",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\sound5",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\sound6",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\SYS",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\TEMP",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\Tools",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ToolsEU",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\ToolsUS",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\USER",
            "C:\\Program Files (x86)\\Steam\\steamapps\\common\\ffxi\\SquareEnix\\FINAL FANTASY XI\\VTABLE.DAT",
        ]
    },
    '2':{
        "context": [
            "MechWarrior Online",
            "MechWarrior Online\\build_info.xml",
            "MechWarrior Online\Engine",
        ],
        "analysis": [
            "Half-Life 2\\bin",
            "Half-Life 2\\bin\\tools\commedit.dll"
        ]
    }

}

Train_Data = {
    '0': {
        "context": [
            "Besiege\\Besiege_Data\\Managed",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "Besiege\\Besiege_Data\\Managed\\System.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.xml"
        ],
        "train": [
            [1.0, 0.0],
        ]
    },
    '1': {
        "context": [
            "Besiege\\Besiege_Data\\Managed",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "Besiege\\Besiege_Data\\Managed\\System.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.xml",
            "Besiege\\Besiege_Data\\Managed\\game.ico"
        ],
        "train": [
            [1.0, 0.0],
            [0.0, 1.0],
        ]
    },
    '2': {
        "context": [
            "Besiege\\Besiege_Data\\Managed",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "Besiege\\Besiege_Data\\Managed\\System.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "Besiege\\Besiege_Data\\Managed\\SaveData.dat"
            "Besiege\\Besiege_Data\\Managed\\LevelData"
        ],
        "train": [
            [0.0, 1.0],
            [0.0, 1.0],
        ]
    },
    '3': {
        "context": [
            "Besiege\\Besiege_Data\\Managed",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-CSharp.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript-firstpass.dll",
            "Besiege\\Besiege_Data\\Managed\\Assembly-UnityScript.dll",
            "Besiege\\Besiege_Data\\Managed\\Boo.Lang.dll",
            "Besiege\\Besiege_Data\\Managed\\DynamicText.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Posix.dll",
            "Besiege\\Besiege_Data\\Managed\\Mono.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\mscorlib.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Configuration.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Core.dll",
            "Besiege\\Besiege_Data\\Managed\\System.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Security.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.dll",
            "Besiege\\Besiege_Data\\Managed\\System.Xml.Linq.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Analytics.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.Networking.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityEngine.UI.dll",
            "Besiege\\Besiege_Data\\Managed\\UnityScript.Lang.dll",
        ],
        "analysis": [
            "Besiege\\Besiege_Data\\Managed\\config.bat"
        ],
        "train": [
            [0.0, 1.0],
        ]
    },
    '4':{
        "context": [
            "BioShock Infinite\\Binaries\\Win32",
            "BioShock Infinite\\Binaries\\Win32\\ApexFrameworkSHIPPING_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\APEX_ClothingSHIPPING_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\binkw32.dll",
            "BioShock Infinite\\Binaries\\Win32\\BioShockInfinite.exe",
            "BioShock Infinite\\Binaries\\Win32\\nvtt.dll",
            "BioShock Infinite\\Binaries\\Win32\\PhysX3_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\steam_api.dll",
        ],
        "analysis": [
            "BioShock Infinite\\Binaries\\Win32\\Benchmark.bat",
        ],
        "train": [
            [1.0, 0.0],
        ]
    },
    '5':{
        "context": [
            "BioShock Infinite\\Binaries\\Win32",
            "BioShock Infinite\\Binaries\\Win32\\ApexFrameworkSHIPPING_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\APEX_ClothingSHIPPING_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\binkw32.dll",
            "BioShock Infinite\\Binaries\\Win32\\BioShockInfinite.exe",
            "BioShock Infinite\\Binaries\\Win32\\nvtt.dll",
            "BioShock Infinite\\Binaries\\Win32\\PhysX3_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\steam_api.dll",
        ],
        "analysis": [
            "BioShock Infinite\\Binaries\\Win32\\Benchmark.bat",
            "BioShock Infinite\\Binaries\\Win32\\game.icon",
        ],
        "train": [
            [1.0, 0.0],
            [0.0, 1.0],
        ]
    },
    '6':{
        "context": [
            "BioShock Infinite\\Binaries\\Win32",
            "BioShock Infinite\\Binaries\\Win32\\ApexFrameworkSHIPPING_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\APEX_ClothingSHIPPING_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\binkw32.dll",
            "BioShock Infinite\\Binaries\\Win32\\BioShockInfinite.exe",
            "BioShock Infinite\\Binaries\\Win32\\nvtt.dll",
            "BioShock Infinite\\Binaries\\Win32\\PhysX3_x86.dll",
            "BioShock Infinite\\Binaries\\Win32\\steam_api.dll",
        ],
        "analysis": [
            "BioShock Infinite\\Binaries\\Win32\\SaveGames.Dat",
        ],
        "train": [
            [0.0, 1.0],
        ]
    },
    '7':{
        "context": [
            "borderlands\\Binaries",
            "borderlands\\Binaries\\binkw32.dll",
            "borderlands\\Binaries\\Borderlands.exe",
            "borderlands\\Binaries\\cudart.dll",
            "borderlands\\Binaries\\dbghelp.dll",
            "borderlands\\Binaries\\fmodex.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleFr.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleGr.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleIt.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleLa.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleSp.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleUk.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleUs.dll",
            "borderlands\\Binaries\\LangSelect.exe",
            "borderlands\\Binaries\\libresample.dll",
            "borderlands\\Binaries\\nvtt.dll",
            "borderlands\\Binaries\\NxCooking.dll",
            "borderlands\\Binaries\\ogg.dll",
            "borderlands\\Binaries\\PhysXCore.dll",
            "borderlands\\Binaries\\PhysXExtensions.dll",
            "borderlands\\Binaries\\SetupHelper.exe",
            "borderlands\\Binaries\\steam.log",
            "borderlands\\Binaries\\SteamAPIUpdater.dll",
            "borderlands\\Binaries\\steam_api.dll",
            "borderlands\\Binaries\\UpdateDLLWrapper.dll",
            "borderlands\\Binaries\\vorbis.dll",
            "borderlands\\Binaries\\vorbisenc.dll",
            "borderlands\\Binaries\\vorbisfile.dll",
            "borderlands\\Binaries\\wxmsw28ud_adv_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_aui_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_core_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_dbgrid_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_gl_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_html_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_media_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_net_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_odbc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_qa_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_richtext_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_xml_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_xrc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_adv_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_aui_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_core_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_dbgrid_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_gl_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_html_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_media_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_net_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_odbc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_qa_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_richtext_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_xml_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_xrc_vc_custom.dll",
        ],
        "analysis": [
            "borderlands\\Binaries\\wxRC",
            "borderlands\\Binaries\\wxRes",
            "borderlands\\Binaries\\Windows",
            "borderlands\\Binaries\\Borderlands.ico",
            "borderlands\\Binaries\\PhysXLocal",
        ],
        "train": [
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],

        ]
    },
    '8':{
        "context": [
            "borderlands\\Binaries",
            "borderlands\\Binaries\\binkw32.dll",
            "borderlands\\Binaries\\Borderlands.exe",
            "borderlands\\Binaries\\cudart.dll",
            "borderlands\\Binaries\\dbghelp.dll",
            "borderlands\\Binaries\\fmodex.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleFr.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleGr.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleIt.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleLa.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleSp.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleUk.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleUs.dll",
            "borderlands\\Binaries\\LangSelect.exe",
            "borderlands\\Binaries\\libresample.dll",
            "borderlands\\Binaries\\nvtt.dll",
            "borderlands\\Binaries\\NxCooking.dll",
            "borderlands\\Binaries\\ogg.dll",
            "borderlands\\Binaries\\PhysXCore.dll",
            "borderlands\\Binaries\\PhysXExtensions.dll",
            "borderlands\\Binaries\\SetupHelper.exe",
            "borderlands\\Binaries\\steam.log",
            "borderlands\\Binaries\\SteamAPIUpdater.dll",
            "borderlands\\Binaries\\steam_api.dll",
            "borderlands\\Binaries\\UpdateDLLWrapper.dll",
            "borderlands\\Binaries\\vorbis.dll",
            "borderlands\\Binaries\\vorbisenc.dll",
            "borderlands\\Binaries\\vorbisfile.dll",
            "borderlands\\Binaries\\wxmsw28ud_adv_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_aui_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_core_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_dbgrid_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_gl_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_html_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_media_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_net_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_odbc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_qa_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_richtext_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_xml_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_xrc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_adv_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_aui_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_core_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_dbgrid_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_gl_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_html_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_media_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_net_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_odbc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_qa_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_richtext_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_xml_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_xrc_vc_custom.dll",
        ],
        "analysis": [
            "borderlands\\Binaries\\bat.bat",
            "borderlands\\Binaries\\wxRes",
            "borderlands\\Binaries\\Windows",
            "borderlands\\Binaries\\Borderlands.ico",
            "borderlands\\Binaries\\PhysXLocal",
            "borderlands\\Binaries\\player.plist",
        ],
        "train": [
            [0.0, 1.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],

        ]
    },
    '9':{
        "context": [
            "borderlands\\Binaries",
            "borderlands\\Binaries\\binkw32.dll",
            "borderlands\\Binaries\\Borderlands.exe",
            "borderlands\\Binaries\\cudart.dll",
            "borderlands\\Binaries\\dbghelp.dll",
            "borderlands\\Binaries\\fmodex.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleFr.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleGr.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleIt.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleLa.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleSp.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleUk.dll",
            "borderlands\\Binaries\\FonixTtsDtSimpleUs.dll",
            "borderlands\\Binaries\\LangSelect.exe",
            "borderlands\\Binaries\\libresample.dll",
            "borderlands\\Binaries\\nvtt.dll",
            "borderlands\\Binaries\\NxCooking.dll",
            "borderlands\\Binaries\\ogg.dll",
            "borderlands\\Binaries\\PhysXCore.dll",
            "borderlands\\Binaries\\PhysXExtensions.dll",
            "borderlands\\Binaries\\SetupHelper.exe",
            "borderlands\\Binaries\\steam.log",
            "borderlands\\Binaries\\SteamAPIUpdater.dll",
            "borderlands\\Binaries\\steam_api.dll",
            "borderlands\\Binaries\\UpdateDLLWrapper.dll",
            "borderlands\\Binaries\\vorbis.dll",
            "borderlands\\Binaries\\vorbisenc.dll",
            "borderlands\\Binaries\\vorbisfile.dll",
            "borderlands\\Binaries\\wxmsw28ud_adv_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_aui_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_core_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_dbgrid_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_gl_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_html_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_media_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_net_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_odbc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_qa_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_richtext_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_xml_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28ud_xrc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_adv_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_aui_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_core_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_dbgrid_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_gl_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_html_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_media_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_net_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_odbc_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_qa_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_richtext_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_xml_vc_custom.dll",
            "borderlands\\Binaries\\wxmsw28u_xrc_vc_custom.dll",
        ],
        "analysis": [
            "borderlands\\Binaries\\ffxivgame.bck",
            "borderlands\\Binaries\\ffxivgame.ver",
            "borderlands\\Binaries\\movie",
            "borderlands\\Binaries\\sqpack",
        ],
        "train": [
            [0.0, 1.0],
            [0.0, 1.0],
            [1.0, 1.0],
            [1.0, 1.0],

        ]
    },
    '10':{
        "context": [
            "FINAL FANTASY XIV - A Realm Reborn\\game",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w32.dll",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w64.dll",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv.exe",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe",
        ],
        "analysis": [
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxivgame.bck",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\fileinfo.fiin",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\movie",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxivgame.ver",
        ],
        "train": [
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
            [1.0, 0.0],
        ]
    },
	'11':{
        "context": [
            "FINAL FANTASY XIV - A Realm Reborn\\game",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w32.dll",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w64.dll",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv.exe",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe",
        ],
        "analysis": [
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxivgame.bck",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\fileinfo.fiin",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\{f4n92df-dgsd}",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\system32",
        ],
        "train": [
            [1.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],
            [1.0, 0.0],
            [0.0, 1.0],
        ]
    },
	'12':{
        "context": [
            "FINAL FANTASY XIV - A Realm Reborn\\game",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w32.dll",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\bink2w64.dll",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv.exe",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\ffxiv_dx11.exe",
        ],
        "analysis": [
            "FINAL FANTASY XIV - A Realm Reborn\\game\\eventvwr.msc",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\appwiz.cpl",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\new_folder",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\personal_data.dat",
            "FINAL FANTASY XIV - A Realm Reborn\\game\\hosts",
        ],
        "train": [
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
        ]
    },
}

Test_Data = {
    '1': {
        "context": [
            "ffxi\\SquareEnix\\FINAL FANTASY XI",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXi.dll",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXiMain.dll",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXiResource.dll",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\FFXiVersions.dll",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\config.sys",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ImeUiDll.dll",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ImeUiDll2.dll",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\polboot.exe",
        ],
        "analysis": [
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_e.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_n.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_ne.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_nw.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_s.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_se.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_sw.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\arw_w.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\file.txt",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\FTABLE.DAT",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\mousehit.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\mousenor.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\mousenor.cur",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\mov",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_e.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_n.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_ne.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_nw.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_s.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_se.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_sw.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\oarw_w.ani",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.cfg",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.rst",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.sin",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.txt",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\patch.ver",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\patch2.cfg",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\polboot.exe.manifest",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM2",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM3",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM4",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM5",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM6",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM7",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ROM8",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\signature.DAT",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\sound",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\sound2",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\sound3",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\sound4",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\sound5",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\sound6",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\SYS",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\TEMP",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\Tools",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ToolsEU",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\ToolsUS",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\USER",
            "ffxi\\SquareEnix\\FINAL FANTASY XI\\VTABLE.DAT",
        ]
    },
    '2':{
        "context": [
            "MechWarrior Online",
            "MechWarrior Online\\build_info.xml",
            "MechWarrior Online\Engine",
        ],
        "analysis": [
            "Half-Life 2\\bin",
            "Half-Life 2\\bin\\tools\commedit.dll"
        ]
    }

}
